server:
  port: 8081

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: 192.168.0.123
    port: 6379
  profiles:
    active: swagger
  swagger:
    active: true